@startuml
skinparam backgroundColor #FFFFFF
skinparam shadowing false

class "Пользователь\n(Магазин)" as Shop {
  имя
  email
  адрес_доставки
  история_заказов
}

class "Пользователь\n(Медицина)" as Med {
  ФИО
  дата_рождения
  группа_крови
  диагнозы
}

class "Пользователь\n(HR)" as HR {
  должность
  отдел
  зарплата
  дата_найма
}

note top : Один и тот же "Пользователь" — разные атрибуты в разных контекстах
@enduml
