@startuml
skinparam backgroundColor #FFFFFF
skinparam shadowing false
hide circle

entity "A" as A1
entity "B" as B1
A1 ||--|| B1 : "1 и только 1"

entity "C" as C1
entity "D" as D1
C1 |o--o| D1 : "0 или 1"

entity "E" as E1
entity "F" as F1
E1 ||--|{ F1 : "1 или много"

entity "G" as G1
entity "H" as H1
G1 ||--o{ H1 : "0 или много"
@enduml
